services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    ###
    ### ! _instanceof only works for services declared in THIS file ! ###
    ###
    _instanceof:
        App\AppBundle\Infrastructure\AppEntityManagerInterface:
            tags: ['app.entity_manager'] # @todo use attributes
        
        App\AppBundle\Infrastructure\AppRepositoryInterface:
            tags: ['app.repository']

    # BUNDLE #
    App\Local\:
        resource: ../../src/Local/

    #################
    # DDD Interface #
    #################
    App\Local\Domain\Manager\RedisManagerInterface: '@App\Local\Infrastructure\Manager\RedisManager'

    #########
    # INFRA #
    #########
    App\Local\Infrastructure\RedisClientInterface:
        factory: '@App\Local\Infrastructure\RedisClientFactory'
