parameters:
    noDoctrineEntityManagerList:
        redis: App\AppData\Infrastructure\Redis\RedisEntityManager

    entityReplicasSupport: 
        App\AppBundle\Domain\Entity\Log: ['sqlite', 'redis']

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # BUNDLE #
    App\AppData\:
        resource: ../../src/AppData/

    App\AppData\Domain\Service\CustomScriptsInterface:
        '@App\AppData\Infrastructure\Service\CustomScripts'

    App\AppData\Infrastructure\Manager\AppSupportRegistry:
        arguments:
            $entityReplicasSupport: '%entityReplicasSupport%'
            $noDoctrineEntityManagerList: '%noDoctrineEntityManagerList%'

    #########
    # INFRA #
    #########
    # @todo remove this factory and select client with config only !
    App\AppData\Infrastructure\Redis\RedisClient:
        arguments:
            $redisClient: "@= 
                parameter('use_redis') === 'local' ? service('snc_redis.local') : (
                    parameter('use_redis') === 'remote' ? service('snc_redis.remote') : null)"
