parameters:
    noDoctrineEntityManagerList:
        redis: App\AppData\Infrastructure\Redis\RedisEntityManager

    entityReplicasSupport: 
        App\AppBundle\Domain\Entity\Log: ['sqlite', 'redis']

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # BUNDLE #
    App\AppData\:
        resource: ../../src/AppData/

    App\AppData\Domain\Service\CustomScriptsInterface:
        '@App\AppData\Infrastructure\Service\CustomScripts'

    App\AppData\Infrastructure\Manager\AppSupportRegistry:
        arguments:
            $entityReplicasSupport: '%entityReplicasSupport%'
            $noDoctrineEntityManagerList: '%noDoctrineEntityManagerList%'

    #########
    # INFRA #
    #########
    App\AppData\Infrastructure\Redis\RedisClient:
        arguments:
            $redisClient: ~

    # APP REGISTRY ###
    # @todo: Use fake Doctrine for tests
    # App\AppData\Infrastructure\Manager\AppEntityManager:
    #     arguments: 
    #         $reg: !tagged_iterator tag
    #     decorates: Doctrine\Common\Persistence\ManagerRegistry
    #     NOT NEEDED arguments: ['@.inner'] # Automatic with default service.yaml
    # App\AppData\Infrastructure\Manager\AppRepositoryRegistry:
    #     arguments:
    #         $repositories: !tagged_iterator app.repository