services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    ###
    ### ! _instanceof only works for services declared in THIS file ! ###
    ###
    _instanceof:
        # App LOGGER used in TextBundle #
        App\AppBundle\Domain\Service\LoggerAwareInterface:
            calls:
                - ['setLogger', ['@app.logger']]

    # BUNDLE #
    App\Text\:
        resource: ../../src/Text/

    # App\Text\Domain\Manager\CommandManager:
    #     arguments:
    #         - !tagged_iterator { tag: app.command_process } # !tagged_iterator app.command_process
