framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        #default_memcached_provider:
        #default_psr6_provider:

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        # cache.adapter.apcu, cache.adapter.system, cache.adapter.filesystem, cache.adapter.psr6, cache.adapter.redis
        # cache.adapter.memcached, cache.adapter.pdo and cache.adapter.doctrine_dbal
        app: cache.adapter.system

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
