doctrine:
    # @see https://symfony.com/doc/current/reference/configuration/doctrine.html

    # DB Abstraction Layer
    dbal:
        # Replace dbname, host and port
        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_mysql
        dbname_suffix: ''
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '6'
        charset: utf8mb4
        memory: true
        driver_class: ~
        wrapper_class: ~

        ### FOR MULTIPLE CONNECTIONS ##
        # default_connection:       default
        # connections:
        #     default:
        #         dbname:           Symfony
        # ###

    # Object Relational Mapping
    orm:
        ### MAPPING ###
        # Loads attribute configuration from the Entity
        # auto_mapping: false
        # mappings:
        #     AppBundle:
        #         type: xml
        #         dir: <SomeResources/config/doctrine>

        # Otherwise
        # SomeEntityNamespace:
        #     type: annotation
        #     dir: '%kernel.project_dir%/src/Entity'
        #     is_bundle: false
        #     prefix: App\Entity
        #     # Gives them an MyApp alias (so you can say things like MyApp:Post)
        #     alias: MyApp
        # ###

        ### SAMPLE attributes ###
        mappings:
            AppBundle:
                # Use AttributeDriver class (with MappingDriverChain)
                alias: AppBundle # Can use "console AppBundle:<entity> --regenerate"
                type: attribute
                dir: 'Entity'
                prefix: 'App\AppBundle' # MUST begin with <mapping-name>\
                is_bundle: true # change 'dir' attribute as relative path 

        # entity_managers:
        #     # This is doctrine.orm.default_entity_manager
        #     default:
        #         #auto_generate_proxy_classes: true
        #         #class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
        #         #default_repository_class:  Doctrine\ORM\EntityRepository

        #         connection: default
        #         naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        #         hydrators: ~
        #         dql: ~
        #         filters: ~
        #         mappings:
        #             App:
        #                 # Use AttributeDriver class (with MappingDriverChain)
        #                 alias: App # Can use "console App:<entity> --regenerate"
        #                 type: attribute 
        #                 dir: '%kernel.project_dir%/src/Entity'
        #                 prefix: 'App\Entity' # MUST begin with <mapping-name>\
        #                 is_bundle: false

when@test:
    doctrine:
        dbal:
            #url: '%env(resolve:DATABASE_URL)%'
            #
            # @todo see why DATABASE_URL doesn't works for tests
            #
            url: "sqlite:///%kernel.project_dir%/var/data.db"
            driver: pdo_sqlite
            server_version: '3'
            charset: utf8mb4
            # "TEST_TOKEN" is typically set by ParaTest
            #dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
