imports:
    - { resource: assets.yml }

# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    # https://symfony.com/doc/current/session.html#store-sessions-in-a-database
    session:
        # PdoSessionHandler, RedisSessionHandler, MemcachedSessionHandler
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    esi: true
    #fragments: true
    php_errors:
        log: true

    # assets:
    #     enabled: true
    #     strict_mode: '%kernel.debug%'
    #     #version_strategy: 'static'
    #     version_format: '%%s?%%s'
    #     # version: 'v1'

    #     packages:
    #         script:
    #             base_path: assets/script
    #         style:
    #             base_path: assets/style

when@test:
    framework:
        test: true
        csrf_protection: false
        session:
            storage_factory_id: session.storage.factory.mock_file
