framework:
    workflows:
        encrypt:
            # logs
            audit_trail: 
                enabled: false
            type: state_machine # One of "workflow"; "state_machine"
            supports:
                - App\Encrypt\Domain\Model\EncryptedData

            # Select which Transition events should be dispatched for this Workflow
            # events_to_dispatch:
                # Examples:
                # - workflow.enter

            places:
                - request
                - processing
                - done

            transitions:
                to_process:
                    from: request
                    to: processing
                to_finish:
                    from: processing
                    to: done
                # An expression to block the transition
                # guard: ~ # Example: "is_fully_authenticated() and is_granted('ROLE_JOURNALIST') and subject.getTitle() == 'My first article'"
                # from:                 []
                # to:                   []
                # metadata:
                    # Examples:
                    # color:               blue
                    # description:         'Workflow to manage article.'

            metadata: ~
                # Examples:
                # color:               blue
                # description:         'Workflow to manage article.'
