api_controllers:
    resource: ../../src/ApiResource/
    type: annotation

controllers:
    resource: ../../src/AppBundle/Controller/
    type: annotation

admin_controllers:
    resource: ../../src/Admin/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
