CREATE TABLE User (
id INT AUTO_INCREMENT NOT NULL, uuid VARCHAR(180) NOT NULL, 
roles JSON NOT NULL, password VARCHAR(255) NOT NULL, 
UNIQUE INDEX UNIQ_2DA17977D17F50A6 (uuid), 
PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

CREATE TABLE Log (
id INT AUTO_INCREMENT NOT NULL, 
level VARCHAR(255) NOT NULL, 
channel VARCHAR(255) NOT NULL, 
message VARCHAR(255) NOT NULL, 
PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;