services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    App\AppBundle\Infrastructure\RedisClientFactory:
        arguments:
            # env function come from ExpressionLanguageProvider.php
            # @todo: use custom expression like "isset()"
            $redisUrl: "@=
                parameter('use_redis') === 'local' && env('REDIS_URL')
                    ? env('REDIS_URL')
                    : (
                        parameter('use_redis') === 'remote' && env('REDIS_REMOTE_URL')
                        ? env('REDIS_REMOTE_URL')
                        : null
                    )"