doctrine:

    # DB Abstraction Layer
    dbal:
        default_connection: default
        connections:
            default: #~ (setted in packages/doctrine.yaml)
                schema_filter: '~^(?!messenger_messages)~'

            sqlite:
                url: '%env(resolve:DEV_SQLITE_URL)%'
                driver: pdo_sqlite
                dbname_suffix: ''
                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                server_version: '3'
                charset: utf8mb4
                memory: true
                driver_class: ~
                wrapper_class: App\AppBundle\Infrastructure\Dbal\ConnectionWrapper
                schema_filter: '~^(?!messenger_messages)~'

    # Object Relational Mapping
    orm:
        default_entity_manager: default
        #auto_generate_proxy_classes: true
        #proxy_namespace: Proxies
        #proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        #class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
        #default_repository_

        # @see https://symfony.com/doc/current/doctrine/multiple_entity_managers.html
        entity_managers:
            default:
                connection: default
                mappings:
                    AppBundle:
                        # Use AttributeDriver class (with MappingDriverChain)
                        alias: AppBundle # Can use "console AppBundle:<entity> --regenerate"
                        prefix: 'App\AppBundle' # MUST begin with <mapping-name>\
                        type: attribute
                        dir: '../../Domain/Entity'
                        is_bundle: true # change 'dir' attribute as relative path

            sqlite:
                connection: sqlite
                # @todo Can we mutualized mapping ? #
                mappings:
                    AppBundle:
                        type: attribute
                        prefix: 'App\AppBundle'
                        dir: '%kernel.project_dir%/src/AppBundle/Domain/Entity'
                        is_bundle: false # change 'dir' attribute as relative path
