# Must be configured to avoir error: "No route found"

api_controllers:
    resource: ../src/ApiResource/
    type: annotation
    prefix: /api

controllers:
    resource: ../src/AppBundle/Controller/
    type: annotation

controllers_admin:
    resource: ../src/Admin/Application/Controller/
    type: annotation