# Must be configured to avoir error: "No route found"
controllers_admin:
    resource: ../src/Admin
    type: attribute

controllers_aws:
    resource: ../src/AwsBundle/Controller
    type: attribute

controllers_data:
    resource: ../src/DataBundle/Controller
    type: attribute

# FRONT
controllers_front:
    resource: ../src/FrontBundle/Controller
    type: attribute

controllers_text:
    resource: ../src/TextBundle/Controller
    type: attribute

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /text
        permanent: true