services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Features\:
        resource: '../features/bootstrap/*'

    App\AppBundle\Domain\Manager\AppDoctrine:
        class: App\Tests\AppDoctrineTestCase
        arguments:
            $replicateEntities: '%replicateEntities%'